# Generated by Django 4.1.7 on 2023-08-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolescreens',
            name='screens',
            field=models.TextField(default='Dashboard,DataAlignment,IndicatorMappingRules,IndicatorComparison,DataQuality,Indicators,AllIndicators,Categories,Security,DataPullSchedule,Roles,Users,PasswordPolicy,Reports', max_length=2500),
        ),
    ]
