# Generated by Django 4.1.7 on 2023-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0002_rolescreens_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolescreens',
            options={'verbose_name_plural': 'Role Access'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
