# Generated by Django 4.1.7 on 2024-04-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0002_alter_rolescreens_screens'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
