# Generated by Django 4.1.7 on 2023-05-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authman', '0006_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
