# Generated by Django 4.0.8 on 2023-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetColumns_Ranaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(default='orglevel2', max_length=500, null=True)),
                ('rename_to', models.CharField(default='county', help_text='Rename columns to a simpler name', max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rename Dataset Columns',
                'db_table': 'dataset_column_renaming',
            },
        ),
        migrations.CreateModel(
            name='KeyComparisonElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.BooleanField(default=True)),
                ('gender', models.BooleanField(default=True)),
                ('similar_words', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Key Comparison Elements',
                'db_table': 'key_comparison_elements',
            },
        ),
        migrations.CreateModel(
            name='MiscSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_25_plus_ages', models.BooleanField(default=True)),
                ('merge_1_to_9_ages', models.BooleanField(default=True)),
                ('max_word_similarity', models.IntegerField(default=30)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Miscleneous Settings',
                'db_table': 'misc',
            },
        ),
        migrations.CreateModel(
            name='SeriesColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datim_main_comparison_column', models.CharField(default='Datim_Disag_Name', help_text='Map indicators to MOH using this column', max_length=255)),
                ('moh_main_comparison_column', models.CharField(default='MOH_Indicator_Name', help_text='Map indicators to Datim using this column', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dataset Series Columns To Map',
                'db_table': 'mapping_series_columns',
            },
        ),
        migrations.CreateModel(
            name='SeriesRegex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group_regex', models.CharField(default='(\\d{2}[+])|(\\d+[-]\\d+)|([<]\\d{1})', help_text='Regex to extract age group', max_length=255)),
                ('gender_regex', models.CharField(default='\\((F|M)\\)|(Male|Female)', help_text='Regex to extract MOH Gender', max_length=1500)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mapping regex definations',
                'db_table': 'series_regex',
            },
        ),
    ]
