# Generated by Django 4.1.7 on 2023-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyComparisonElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.BooleanField(default=True)),
                ('gender', models.BooleanField(default=True)),
                ('similar_words', models.BooleanField(default=True)),
                ('max_similar_words', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Key Comparison Elements',
                'db_table': 'key_comparison_elements',
            },
        ),
        migrations.DeleteModel(
            name='GruopSeriesData',
        ),
        migrations.RemoveField(
            model_name='seriescolumns',
            name='datim_cols',
        ),
        migrations.RemoveField(
            model_name='seriescolumns',
            name='datim_moh_columns_to_display',
        ),
        migrations.RemoveField(
            model_name='seriescolumns',
            name='moh_cols',
        ),
        migrations.RemoveField(
            model_name='seriesregex',
            name='regex_name',
        ),
        migrations.RemoveField(
            model_name='seriesregex',
            name='regex_pattern',
        ),
        migrations.AddField(
            model_name='seriesregex',
            name='age_group_regex',
            field=models.CharField(default='(\\d{2}[+])|(\\d+[-]\\d+)|([<]\\d{1})', help_text='Regex to extract age group', max_length=255),
        ),
        migrations.AddField(
            model_name='seriesregex',
            name='gender_regex',
            field=models.CharField(default='\\((F|M)\\)|(Male|Female)', help_text='Regex to extract MOH Gender', max_length=1500),
        ),
    ]
