# Generated by Django 4.1.7 on 2023-03-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_rules', '0003_remove_datasetcolumns_ranaming_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcolumns_ranaming',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='keycomparisonelements',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seriescolumns',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seriesregex',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
