# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_rules', '0004_datasetcolumns_ranaming_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_25_plus_ages', models.BooleanField(default=True)),
                ('merge_1_to_9_ages', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Miscleneous Settings',
                'db_table': 'misc',
            },
        ),
    ]
