# Generated by Django 4.1.7 on 2023-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_rules', '0005_miscsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscsettings',
            name='max_word_similarity',
            field=models.IntegerField(default=30),
        ),
    ]
