# Generated by Django 4.1.7 on 2023-03-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_rules', '0006_miscsettings_max_word_similarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keycomparisonelements',
            name='max_similar_words',
        ),
    ]
