# Generated by Django 3.2.13 on 2022-08-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Mapping_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mapping/')),
                ('final_file', models.FileField(blank=True, null=True, upload_to='final/')),
            ],
            options={
                'verbose_name_plural': 'Data Mapping Files',
                'db_table': 'data_mapping_files',
            },
        ),
        migrations.CreateModel(
            name='indicatorGroups',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastUpdated', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'indicators groups',
                'db_table': 'moh_indicator_groups',
            },
        ),
        migrations.CreateModel(
            name='indicatorType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'indicators types',
                'db_table': 'moh_indicator_types',
            },
        ),
        migrations.CreateModel(
            name='mapped_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Mapped', models.DateTimeField(auto_now_add=True, null=True)),
                ('DATIM_Indicator_Category', models.CharField(blank=True, max_length=255, null=True)),
                ('DATIM_Indicator_ID', models.CharField(blank=True, max_length=500, null=True)),
                ('DATIM_Disag_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('DATIM_Disag_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Operation', models.CharField(blank=True, max_length=20, null=True)),
                ('MOH_Indicator_Name', models.CharField(blank=True, max_length=1500, null=True)),
                ('MOH_Indicator_ID', models.CharField(blank=True, max_length=500, null=True)),
                ('MOH_Disag_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('MOH_Disag_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Disaggregation_Type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fianl Mapped Data',
                'db_table': 'datim_mapped_data',
            },
        ),
        migrations.CreateModel(
            name='middleware_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syncdata', models.BooleanField(default=False)),
                ('client_url', models.URLField(blank=True, default='https://test.hiskenya.org/dhiske/', null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Sync Settings',
                'db_table': 'middleware_settings',
            },
        ),
        migrations.CreateModel(
            name='schedule_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.TimeField()),
                ('shedule_description', models.CharField(blank=True, default='Weekely  data sync', max_length=255, null=True)),
                ('sync_m', models.IntegerField(default=0)),
                ('sync_t', models.IntegerField(default=0)),
                ('sync_w', models.IntegerField(default=0)),
                ('sync_th', models.IntegerField(default=0)),
                ('sync_f', models.IntegerField(default=0)),
                ('sync_s', models.IntegerField(default=0)),
                ('sync_su', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Schedule Settings',
                'db_table': 'schedule_settings',
            },
        ),
        migrations.CreateModel(
            name='total_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Total Records',
                'db_table': 'khis_total_records',
            },
        ),
        migrations.CreateModel(
            name='indicators',
            fields=[
                ('MOH_Indicator_ID', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('MOH_Indicator_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('shortName', models.CharField(blank=True, max_length=500, null=True)),
                ('displayName', models.CharField(blank=True, max_length=500, null=True)),
                ('displayShortName', models.CharField(blank=True, max_length=500, null=True)),
                ('displayNumeratorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('denominatorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('displayDenominatorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('numeratorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('dimensionItem', models.CharField(blank=True, max_length=500, null=True)),
                ('displayFormName', models.CharField(blank=True, max_length=500, null=True)),
                ('numerator', models.CharField(blank=True, max_length=2500, null=True)),
                ('denominator', models.CharField(blank=True, max_length=2500, null=True)),
                ('dimensionItemType', models.CharField(blank=True, max_length=500, null=True)),
                ('indicatorGroups', models.ManyToManyField(blank=True, null=True, to='api.indicatorGroups')),
                ('indicatorType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.indicatortype')),
            ],
            options={
                'verbose_name_plural': 'indicators',
                'db_table': 'moh_indicators',
            },
        ),
    ]
