# Generated by Django 3.2.13 on 2022-07-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indicatorGroups',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastUpdated', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'indicators groups',
                'db_table': 'moh_indicator_groups',
            },
        ),
        migrations.CreateModel(
            name='indicatorType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'indicators types',
                'db_table': 'moh_indicator_types',
            },
        ),
        migrations.CreateModel(
            name='indicators',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('shortName', models.CharField(blank=True, max_length=500, null=True)),
                ('displayName', models.CharField(blank=True, max_length=500, null=True)),
                ('displayShortName', models.CharField(blank=True, max_length=500, null=True)),
                ('displayNumeratorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('denominatorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('displayDenominatorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('numeratorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('dimensionItem', models.CharField(blank=True, max_length=500, null=True)),
                ('displayFormName', models.CharField(blank=True, max_length=500, null=True)),
                ('numerator', models.CharField(blank=True, max_length=2500, null=True)),
                ('denominator', models.CharField(blank=True, max_length=2500, null=True)),
                ('dimensionItemType', models.CharField(blank=True, max_length=500, null=True)),
                ('indicatorGroups', models.ManyToManyField(blank=True, null=True, to='api.indicatorGroups')),
                ('indicatorType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.indicatortype')),
            ],
            options={
                'verbose_name_plural': 'indicators',
                'db_table': 'moh_indicators',
            },
        ),
    ]
