# Generated by Django 3.2.13 on 2022-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_mapping_files',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='mapping/final/%Y-%m-%d/'),
        ),
    ]
