# Generated by Django 4.1.7 on 2023-05-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concodance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('percentage', models.DecimalField(decimal_places=2, default=90.0, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concodance', to='api.counties')),
            ],
            options={
                'verbose_name_plural': 'Concodance',
                'db_table': 'concodance',
            },
        ),
    ]
