# Generated by Django 3.2.13 on 2022-07-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='middleware_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syncdata', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Middleware Settings',
                'db_table': 'middleware_settings',
            },
        ),
    ]
