# Generated by Django 4.1.7 on 2023-03-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final_comparison_data',
            old_name='created',
            new_name='create_date',
        ),
    ]
