# Generated by Django 4.1.7 on 2023-08-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_mapping_files',
            name='mapping_files',
            field=models.FileField(upload_to='mapping_files/%Y%'),
        ),
    ]
