# Generated by Django 3.2.13 on 2022-08-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mapped_data',
            table='mapped_data',
        ),
    ]
