# Generated by Django 3.2.13 on 2022-08-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mapped_data_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapped_data',
            name='MOH_Disag_ID',
        ),
        migrations.RemoveField(
            model_name='mapped_data',
            name='MOH_Disag_Name',
        ),
    ]
