# Generated by Django 3.2.13 on 2022-09-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220919_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final_comparison_data',
            old_name='faclity',
            new_name='facility',
        ),
    ]
