# Generated by Django 4.1.7 on 2023-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_concodance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concodance',
            name='period',
        ),
        migrations.AddField(
            model_name='concodance',
            name='indicator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concodance',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concodance',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
