# Generated by Django 3.2.13 on 2022-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_middleware_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middleware_settings',
            options={'verbose_name_plural': 'Data Sync Settings'},
        ),
        migrations.AddField(
            model_name='middleware_settings',
            name='client_url',
            field=models.URLField(default='https://test.hiskenya.org/dhiske/'),
        ),
    ]
