# Generated by Django 4.1.7 on 2023-08-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_data_mapping_files_mapping_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_mapping_files',
            name='final_comparison',
        ),
        migrations.RemoveField(
            model_name='data_mapping_files',
            name='final_mapped',
        ),
    ]
