# Generated by Django 3.2.13 on 2022-09-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_faclity_final_comparison_data_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_comparison_data',
            name='DATIM_Disag_ID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='final_comparison_data',
            name='DATIM_Disag_Name',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
