# Generated by Django 4.1.7 on 2023-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_concodance_period_concodance_indicator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counties',
            name='facilities',
            field=models.ManyToManyField(to='api.facilities'),
        ),
    ]
