# Generated by Django 4.1.7 on 2023-08-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_data_mapping_files_final_comparison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_mapping_files',
            name='mapping_files',
            field=models.FileField(upload_to='mapping_files/%Y'),
        ),
    ]
