# Generated by Django 3.2.13 on 2022-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220719_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Total Records',
                'db_table': 'khis_total_records',
            },
        ),
        migrations.AlterField(
            model_name='middleware_settings',
            name='client_url',
            field=models.URLField(blank=True, default='https://test.hiskenya.org/dhiske/', null=True),
        ),
    ]
