# Generated by Django 4.1.7 on 2023-08-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_data_mapping_files_mapping_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_mapping_files',
            old_name='mapping_files',
            new_name='mapping_file',
        ),
    ]
