# Generated by Django 3.2.13 on 2022-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220926_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_comparison_data',
            name='concodance',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='final_comparison_data',
            name='khis_minus_datim',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='final_comparison_data',
            name='weight',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
