# Generated by Django 3.2.13 on 2022-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220723_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.TimeField()),
                ('shedule_description', models.CharField(default='Weekely  data sync', max_length=255)),
                ('sync_m', models.BooleanField(default=False)),
                ('sync_t', models.BooleanField(default=False)),
                ('sync_w', models.BooleanField(default=False)),
                ('sync_th', models.BooleanField(default=False)),
                ('sync_f', models.BooleanField(default=False)),
                ('sync_s', models.BooleanField(default=False)),
                ('sync_su', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Schedule Settings',
                'db_table': 'schedule_settings',
            },
        ),
    ]
