# Generated by Django 3.2.13 on 2022-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220926_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='counties',
            fields=[
                ('county_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='indicator_category',
            fields=[
                ('category_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Indicator Categories',
                'db_table': 'indicator_category',
            },
        ),
    ]
