# Generated by Django 4.1.7 on 2023-09-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_mapping_files_data_mapping_files_mapping_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indicator_category',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='denominator',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='denominatorDescription',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='dimensionItem',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='dimensionItemType',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='displayDenominatorDescription',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='displayFormName',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='displayNumeratorDescription',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='displayShortName',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='indicatorGroups',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='indicatorType',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='numerator',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='numeratorDescription',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='shortName',
        ),
        migrations.AlterField(
            model_name='middleware_settings',
            name='client_url',
            field=models.URLField(blank=True, default='http://nhdc-kmhfl.health.go.ke/api/analytics.json?dimension=dx:W0ChhvyVtSX;EXmKDudsMNb;fuX0Qzg218I;fXErbzykgKz;kAvepmaQr9c;WOjriy3w7Fh;NYkr7LlxmUg;qw7eJpLE3vK;du5RMT3aecB;wu0ITFRjUzF;D9YwtS6RhQ1;xMNhnyu7vm1;kLXGWRLzCAw;oCFXmpol7D8;F9OR49Lc1aR;cBTa1jVzT8f;J4vNm7YEkdj;M5zablilTPO;dlldM4hP2Wk;vRVLmMCRuN9;fqj4xHg5t5t;vxJMFFkYUsI;Pbl9S4jD6sw;Kb5NZ5AadY3;tv9aE5k0IqF;usVko3BNxUz;EzuWF48G6ep;jF9pdL3SuHL;cr3CkBQcqGI;ZG5LOYaEecn;Te9pM8UoINV;OePJt8CcZ0d;lj9QYJqS7bN;gMICOUtzqRb;XiRbc0DSMOH;YXJf27jfkvS;JiuqbydCIcy;pkShOkgNQt2;atSQz5O7e2A;gTkVw97FnQK;Yk5WVF4EQoX;kmuBTU9NAjw;G7zACbrJMmY;Th97Ccd4BuJ;OYGWqG4HnBZ;M6hV3ObOCHV;NOga2tabGrd;q50r2FWg6de;hrRIahUNIDc;l2OiHQroa5M&dimension=pe:2022Q4;2023Q1;2023Q2;2023Q3&tableLayout=true&rows=pe&columns=dx&skipRounding=false&completedOnly=false&filter=ou:{org}', null=True),
        ),
        migrations.DeleteModel(
            name='indicatorGroups',
        ),
    ]
