# Generated by Django 3.2.13 on 2022-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_schedule_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_su',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_th',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule_settings',
            name='sync_w',
            field=models.IntegerField(default=0),
        ),
    ]
