# Generated by Django 5.0.4 on 2024-04-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_indicator_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='middleware_settings',
        ),
        migrations.DeleteModel(
            name='schedule_settings',
        ),
    ]
