# Generated by Django 3.2.13 on 2022-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_counties_indicator_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_comparison_data',
            name='Date_Mapped',
        ),
        migrations.AddField(
            model_name='final_comparison_data',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
