# Generated by Django 5.0.4 on 2024-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_middleware_settings_delete_schedule_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='counties',
            name='org_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcounties',
            name='org_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='org_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
