# Generated by Django 4.1.7 on 2024-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/attachments'),
        ),
    ]
