# Generated by Django 4.1.7 on 2023-03-17 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notified_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
