# Generated by Django 4.1.7 on 2023-03-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_user_notifications_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
