# Generated by Django 5.0.4 on 2024-04-08 13:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='email_message_template',
            field=tinymce.models.HTMLField(default="                                     Dear {County_Administrator_Name},I hope this email finds you well.                                    This is a notification to bring to your attention some missed opportunities that have been identified within our county's operations. Upon review of recent data and analysis, it has become apparent that certain areas have not been fully optimized, potentially resulting in lost efficiency and effectiveness."),
        ),
    ]
